### ISSUE TITLE
OpenShift Console URL is wrong

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-operator#13]
The OpenShift Console URL configured in Launcher came up as an incorrect 172.30.0.1 address and doesn't match the minishift console URL.

**Comment by ia3andy** [comment]
It now works with the consoleUrl set in the CR:
![image](https://user-images.githubusercontent.com/2223984/54985879-f6cdd100-4fb1-11e9-9007-622f49d5eb6c.png)

CR looks like this:
![image](https://user-images.githubusercontent.com/2223984/54985940-09480a80-4fb2-11e9-83bc-5003e83dc37e.png)

@gastaldi but the backend fails to create when the consoleUrl is not set:
```
2019-03-23 07:47:05,944 WARNING [launch] (default task-2) Projectile LauncherCreateProjectile{id=80662fca-3def-4fc3-9d35-cc9457d16543, startOfStep=0, projectLocation=/tmp/projectDir925158049933794753/interesting-society, booster=null, openShiftProjectName=interesting-society, gitRepositoryName=interesting-society, gitOrganization=null, gitRepositoryDescription=Generated by the Red Hat Developer Launcher (https://developers.redhat.com/launch )} failed to launch. Time Elapsed: 00:00:06.310: java.lang.RuntimeException: java.net.MalformedURLException
--
  | at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.<init>(Fabric8OpenShiftServiceImpl.java:101)
  | at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceFactory.create(Fabric8OpenShiftServiceFactory.java:55)
  | at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceFactory.create(Fabric8OpenShiftServiceFactory.java:25)
  | at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceFactory$Proxy$_$$_WeldClientProxy.create(Unknown Source)
  | at io.fabric8.launcher.web.producers.OpenShiftServiceProducer.getOpenShiftService(OpenShiftServiceProducer.java:82)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
  | at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
  | at org.jboss.weld.injection.producer.ProducerMethodProducer.produce(ProducerMethodProducer.java:103)
  | at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:161)
  | at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:180)
  | at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
  | at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
  | at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
  | at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
  | at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
  | at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
  | at io.fabric8.launcher.service.openshift.api.OpenShiftService$1403678796$Proxy$_$$_WeldClientProxy.findProject(Unknown Source)
  | at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.createOpenShiftProject(OpenShiftSteps.java:58)
  | at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:115)
  | at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:38)
  | at io.fabric8.launcher.web.endpoints.AbstractLaunchEndpoint.doLaunch(AbstractLaunchEndpoint.java:46)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint$Proxy$_$$_WeldSubclass.doLaunch(Unknown Source)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint.uploadZip(LaunchEndpoint.java:129)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint$Proxy$_$$_WeldSubclass.uploadZip$$super(Unknown Source)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
  | at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
  | at org.hibernate.validator.cdi.internal.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:79)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
  | at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
  | at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
  | at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
  | at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
  | at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint$Proxy$_$$_WeldSubclass.uploadZip(Unknown Source)
  | at io.fabric8.launcher.web.endpoints.LaunchEndpoint$Proxy$_$$_WeldClientProxy.uploadZip(Unknown Source)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:399)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:363)
  | at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:365)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
  | at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:310)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439)
  | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
  | at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
  | at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
  | at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
  | at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
  | at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
  | at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
  | at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
  | at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.fabric8.launcher.web.providers.CorsFilter.doFilter(CorsFilter.java:49)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.fabric8.launcher.web.providers.gzip.GZipFilter.doFilter(GZipFilter.java:42)
  | at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
  | at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
  | at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
  | at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
  | at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
  | at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
  | at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:61)
  | at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
  | at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
  | at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
  | at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
  | at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
  | at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
  | at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
  | at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
  | at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
  | at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
  | at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
  | at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
  | at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
  | at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
  | at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
  | at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
  | at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
  | at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
  | at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
  | at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
  | at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
  | at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
  | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
  | at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: java.net.MalformedURLException
  | at java.net.URL.<init>(URL.java:627)
  | at java.net.URL.<init>(URL.java:490)
  | at java.net.URL.<init>(URL.java:439)
  | at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.<init>(Fabric8OpenShiftServiceImpl.java:99)
  | ... 121 more
  | Caused by: java.lang.NullPointerException
  | at java.net.URL.<init>(URL.java:532)
  | ... 124 more
  | 2019-03-23 07:47:05,997 INFO  [MissionControlStatusEndpoint] (default task-2) WebSocket session closed: 80662fca-3def-4fc3-9d35-cc9457d16543


```
